language: python
python:
 - "3.5"
cache: pip
services:
  - postgresql
install:
 - pip install -r requirements.txt
 - pip install coveralls
before_script:
   - export APP_SETTINGS='development'
   - export SECRET_KEY='thisisasecretkey'
   - export DB_NAME="test_dtb"
   - export DB_HOST="localhost"
   - export DB_USER="hesbon"
   - export DB_PASSWORD="5600"
   - psql -c 'create database test_dtb;' -U hesbon
script:
 - pytest
 - pytest --cov=app
after_success:
 - coveralls
  