language: python
python:
- "3.6"
cache: pip
install:
- pip install -r requirements.txt
before_script:
  - export SECRET_KEY="secret"
script:
- pytest
- pytest --cov=app -v -W error::UserWarning
after_success:
- coveralls